program: train.py
method: bayes
metric:
  goal: minimize
  name: Xmax Loss
parameters:
  lr_scale:
    distribution: q_uniform
    min: 1
    max: 5
    q: 1
  lr_decay:
    values : [0.1, 0.33, 0.5, 0.7]
  batch_size:
    values : [32, 64, 128]
  flu_weight:
    min: 0.000000000000001
    max: 0.0000000001
  weight_decay:
    min: 0.0000000001
    max: 0.01

early_terminate:
  type: hyperband
  s: 10
  eta: 2
  min_iter: 20
