program: train.py
method: bayes
metric:
  goal: minimize
  name: Test Loss
parameters:
  lr_scale:
    distribution: q_uniform
    min: 10
    max: 150
    q: 10
  batch_size:
    values : [4, 8, 16, 32, 64]
  lr:
    min: 0.00001
    max: 0.001
  weight_decay:
    min: 0.0000000001
    max: 0.01

early_terminate:
  type: hyperband
  s: 10
  eta: 2
  min_iter: 20
